version: '3.4'

x-logging:
  &default-logging
  driver: journald


services:
  nzyme_tap_plugin:
    container_name: nzyme-tap-plugin
    build:
      context: .
    logging: *default-logging
    cap_add:
      - NET_ADMIN
    network_mode: host
    volumes:
      - "$SUPERDIR/configs/plugins/nzyme/nzyme-tap.conf:/etc/nzyme/nzyme-tap.conf"
